version: '3.8'

services:
  image_service:
    build:
      context: ./image_service
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./image_service:/app

  login_service:
    build:
      context: ./login_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./login_service:/app

  event_service:
    build:
      context: ./event_service
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./event_service:/app

  gateway_service:
    build:
      context: ./gateway_service
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./gateway_service:/app
