version: '3.8'

services:
  image_service:
    build:
      context: ./image_service
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./image_service:/app

  login_service:
    build:
      context: ./login_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./login_service:/app
